// <auto-generated />
using CityProject_WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CityProject_WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("CityProject_WebAPI.Models.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CustoCidadeUS")
                        .HasColumnType("REAL");

                    b.Property<int>("EstadoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Populacao")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("Cidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustoCidadeUS = 16189204404.0,
                            EstadoId = 1,
                            Nome = "Porto Alegre",
                            Populacao = 1488252
                        },
                        new
                        {
                            Id = 2,
                            CustoCidadeUS = 5584959102.0,
                            EstadoId = 2,
                            Nome = "Florianópolis",
                            Populacao = 508826
                        },
                        new
                        {
                            Id = 3,
                            CustoCidadeUS = 6305506779.0,
                            EstadoId = 3,
                            Nome = "Londrina",
                            Populacao = 575377
                        });
                });

            modelBuilder.Entity("CityProject_WebAPI.Models.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CustoEstadoUS")
                        .HasColumnType("REAL");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Populacao")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustoEstadoUS = 16189204404.0,
                            Nome = "Rio Grande do Sul",
                            Populacao = 1488252
                        },
                        new
                        {
                            Id = 2,
                            CustoEstadoUS = 5584959102.0,
                            Nome = "Santa Catarina",
                            Populacao = 508826
                        },
                        new
                        {
                            Id = 3,
                            CustoEstadoUS = 6305506779.0,
                            Nome = "Paraná",
                            Populacao = 575377
                        });
                });

            modelBuilder.Entity("CityProject_WebAPI.Models.ParametroCusto", b =>
                {
                    b.Property<double>("Desconto")
                        .HasColumnType("REAL");

                    b.Property<double>("PorPessoa")
                        .HasColumnType("REAL");

                    b.Property<int>("ValorCorte")
                        .HasColumnType("INTEGER");

                    b.ToTable("ParametroCustos");
                });

            modelBuilder.Entity("CityProject_WebAPI.Models.Cidade", b =>
                {
                    b.HasOne("CityProject_WebAPI.Models.Estado", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
